repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: bash -c 'source .venv/bin/activate && pytest'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]